#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Initialize counter
counter=0

# Loop until counter is equal to 10
until [ $counter -eq 10 ]; do
    echo "Best School"
    # Increment counter
    ((counter++))
done

